### PR TITLE
Expect `Info.plist` in correct location

### LINKED ISSUE #73: Error: The file “Info.plist” couldn’t be opened
I have an issue with #69, #70
in added `verifyBundleVersion` function
I have `plistURL` value "file:///XXXX/Dependencies/macOS/Result.framework/Info.plist"
and there is no "Info.plist" at all here so reading the file launch an error

I have one into  "file:///XXXX/Dependencies/macOS/Result.framework/Versions/A/Resources/Info.plist"

only have symbolic link and Versions
```swift
Headers -> Versions/Current/Headers
Modules -> Versions/Current/Modules
Resources -> Versions/Current/Resources
Result -> Versions/Current/Result
```

The framework has been build using carthage 0.33.0 as I see in the log after removing accio cache

_I use Xcode 10.3 so maybe something change, because I have old carthage build by me with command line, with an Info.plist at framework root folder_

So to reproduce accio cache must be removed

Maybe it is a carthage issue if the Info.plist must be at root, but if not mandatory this is an accio issue

### PR DESCRIPTION
**Pull request by tcurdt**
According to https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html the correct location for the `Info.plist` is
`FRAMEWORK.framework/Resources/Info.plist`. Yet the verification code was expecting it at `FRAMEWORK.framework/Info.plist` and failed the integration into the Xcode project.

The PR adjusts the location and `swift test` passes. It also works in my test project. This should fix #73 and #76

### CODE REVIEW

File: Sources/AccioKit/Services/XcodeProjectIntegrationService.swift [hunk 1]
```diff
@@ -244,7 +244,7 @@ final class XcodeProjectIntegrationService {
     }
 
     private func verifyBundleVersion(of product: FrameworkProduct) throws {
-        let plistURL = product.frameworkDirUrl.appendingPathComponent("Info.plist")
+        let plistURL = product.frameworkDirUrl.appendingPathComponent("Resources").appendingPathComponent("Info.plist")
```
Comment (Jeehut) [inline Sources/AccioKit/Services/XcodeProjectIntegrationService.swift]: This can be simplified to `appendingPathComponent("Resources/Info.plist")`.

**Review by Jeehut — COMMENTED** [review]
Thanks for the PR, looks good overall. Just one thing: Are you sure that the path is correct for each target OS? Could it be, that it's `Resources/Info.plist` for macOS targets and `Info.plist` for others?

If so, we should update the code to reflect that change. We should definitely verifiy if this code also works with iOS target for example.

File: Sources/AccioKit/Services/XcodeProjectIntegrationService.swift (hunk 1 above)
Comment (tcurdt) [reply Sources/AccioKit/Services/XcodeProjectIntegrationService.swift]: While that is true both `Resources` and `Info.plist` are individual path components as by the definition of the Apple API as in https://developer.apple.com/documentation/foundation/nsstring/1414489-pathcomponents 

While in this case irrelevant it manually bakes in the path separator.
I would consider it bad practice - but no problem to change this.

**Comment by tcurdt** [comment]
I was wondering the very same thing about the location of the `Info.plist`.
The documentation is a big vague here https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW26

For one it says:

> Bundle structures can vary depending on the type of the bundle and the target platform. The following sections describe the bundle structures used most commonly in both macOS and iOS.

yet the following suggests that the `Resources/Info.plist` is the place to check

> The system identifies a framework bundle by the .framework extension on its directory name. The system also uses the Info.plist file inside the framework’s Resources directory to gather information about the configuration of the framework

(otherwise framework version also would not work).

That said I checked what I have on disk and found these examples for iOS

```
/System/iOSSupport/System/Library/Frameworks/WebKit.framework/Versions/A/Resources/Info.plist
```

```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/AVFoundation.framework/Info.plist
```

To me this suggests that altering the behaviour per target of even better checking in both places could be the best strategy.

**Comment by tcurdt** [comment]
How do we go forward? Should amend the PR to support both locations, @Dschee?

**Comment by Jeehut** [comment]
Can't we just make Accio more resilient against the placement of the Info.plist file in general? E.g. by checking multiple places (maybe even regardless of the target platform? or by having a different check order per platform?) and use whatever we find. As an additional step, couldn't we simply create a basic Info.plist file if none is existing where we expect one?

As far as I remember, this was exactly the planned approach of @mrylmz. He probably just didn't have the time to finish it or maybe he just didn't think of macOS targets? I don't remember in detail, but feel free to take the approach suggested above. Then I think, we can safely merge this.

**Comment by mrylmz** [comment]
@Dschee there is a difference between a project Info.plist for building and a Info.plist of a build Framework, they contain different informations and as i know the final Info.plist of the build Framework is guaranteed to be existend. 

It would be ok if we just check multiple known Info.plist locations as solution.

**Comment by Jeehut** [comment]
Okay, then let's opt for that.

**Comment by tcurdt** [comment]
@mrylmz If there is a difference the question is whether we need to handle the content differently depending on where they are. I didn't check that. Do you have more information on that?

**Comment by tcurdt** [comment]
I've updated the PR to reflect the agreed upon path forward. HTH

File: Sources/AccioKit/Services/XcodeProjectIntegrationService.swift [hunk 2]
```diff
@@ -244,17 +244,25 @@ final class XcodeProjectIntegrationService {
     }
 
     private func verifyBundleVersion(of product: FrameworkProduct) throws {
```
Comment (Jeehut) [inline Sources/AccioKit/Services/XcodeProjectIntegrationService.swift]: Why is this called "verify" when it also actually updates the Info.plist file? Maybe it should be `ensureBundleVersionExistence`.

**Review by Jeehut — COMMENTED** [review]
Looks good to me. Could you add an entry to the CHANGELOG.md?

File: Sources/AccioKit/Services/XcodeProjectIntegrationService.swift (hunk 2 above)
Comment (tcurdt) [reply Sources/AccioKit/Services/XcodeProjectIntegrationService.swift]: Ask already hinted in the commit message I agree and will change it.

**Comment by tcurdt** [comment]
I've updated the PR as suggested.

**Comment by tcurdt** [comment]
@Dschee anything else that needs fixing so this can be merged?

**Review by Jeehut — APPROVED** [review]
Looking good, I think we can merge. Thanks! 💯
