### PR TITLE
Fix missing CFBundleVersion for dependencies

### LINKED ISSUE #69: Missing CFBundleVersion in Info.plist of frameworks
If framework dependencies are build by generating a Xcode project with the swift package manager, then the CFBundleVersion key will not be set which causes app store distribution problems.

### PR DESCRIPTION
**Pull request by mrylmz**
Closes #69

### CODE REVIEW

File: Sources/AccioKit/Services/XcodeProjectIntegrationService.swift [hunk 1]
```diff
@@ -241,4 +242,19 @@ final class XcodeProjectIntegrationService {
 
         try projectFile.write(path: Path(xcodeProjectPath), override: true)
     }
+
+    private func verifyBundleVersion(of product: FrameworkProduct) throws {
+        let plistURL = product.frameworkDirUrl.appendingPathComponent("Info.plist")
+        let data = try Data(contentsOf: plistURL)
+        var format: PropertyListSerialization.PropertyListFormat = .binary
+        var plist = try PropertyListSerialization.propertyList(from: data, options: [.mutableContainersAndLeaves], format: &format) as! [String: Any]
```
Comment (fredpi) [inline Sources/AccioKit/Services/XcodeProjectIntegrationService.swift:250]: Why use a force-cast here?

File: Sources/AccioKit/Services/XcodeProjectIntegrationService.swift [hunk 2]
```diff
@@ -241,4 +242,19 @@ final class XcodeProjectIntegrationService {
 
         try projectFile.write(path: Path(xcodeProjectPath), override: true)
     }
+
+    private func verifyBundleVersion(of product: FrameworkProduct) throws {
+        let plistURL = product.frameworkDirUrl.appendingPathComponent("Info.plist")
+        let data = try Data(contentsOf: plistURL)
```
Comment (fredpi) [inline Sources/AccioKit/Services/XcodeProjectIntegrationService.swift:248]: If the Info.plist file doesn't exist at all, as is the case for [SwiftEntryKit](https://github.com/huri000/SwiftEntryKit/tree/master/Source), we should create it.

Does this initializer `throw` or does it return empty `Data` if the file is missing? If the latter is the case, one would need to first create the file, right?

**Review by fredpi — CHANGES_REQUESTED** [review]

File: Sources/AccioKit/Services/XcodeProjectIntegrationService.swift (hunk 1 above)
Comment (mrylmz) [reply Sources/AccioKit/Services/XcodeProjectIntegrationService.swift:250]: Because the cast cannot fail

File: Sources/AccioKit/Services/XcodeProjectIntegrationService.swift (hunk 2 above)
Comment (mrylmz) [reply Sources/AccioKit/Services/XcodeProjectIntegrationService.swift:248]: No the Info.plist file will always exist in the final `MyDependency.framework` folder, only the key `CFBundleVersion` is missing if the project it self is build without having a `Info.plist` file.

**Review by fredpi — APPROVED** [review]

**Comment by fredpi** [comment]
@mrylmz Would you mind adding a changelog entry? :)

**Comment by Jeehut** [comment]
A test for the new method would be great too, one for the case when there is a `CFBundleVersion` set and one for when it's not.
