### PR TITLE
Re-download checkout if failing to reset

### LINKED ISSUE #27: Error reverting changes in the checkouts directory
In my current configuration (with only 1 package), I somehow managed to break the `✨  Reverting any changes in the checkouts directory ...` step. The following problem occurs: `An error occurred: Command '/bin/bash -c "git -C '/[MyProjectPath]/.accio/checkouts/PMJSON' reset HEAD --hard --quiet 2> /dev/null"' returned with error code 128.`

When I copy this repo to another folder and run the failing command (`git -C '[NewPath]/PMJSON' reset HEAD --hard`) manually, there's still an error: `fatal: Could not parse object 'HEAD'.`

Maybe this problem is related to the fact that after initializing accio and then switching to a branch where it wasn't installed yet, I performed a `Reset All` of the original repo via Sourcetree to reset the `.accio` folder. Maybe this had an effect on the recursive subrepos (those within `.accio/checkouts`), so that after switching to the accio branch again, running `accio install` failed. Still weird, that the checkouts folder survived the git reset... 🤔

### PR DESCRIPTION
**Pull request by fredpi**
Fixes #27 using a pragmatic approach. 

As Accio currently fails to build (maybe only on my machine?) due to a build error in xcodeproj, this is not tested yet.

### CODE REVIEW

File: Sources/AccioKit/Commands/Protocols/DependencyInstaller.swift [hunk 1]
```diff
@@ -34,9 +34,16 @@ extension DependencyInstaller {
...
-                    try bash("git -C '\(frameworkCheckoutPath)' clean -fdX --quiet 2> /dev/null")
+                    do {
+                        try bash("git -C '\(frameworkCheckoutPath)' reset HEAD --hard --quiet 2> /dev/null")
+                        try bash("git -C '\(frameworkCheckoutPath)' clean -fd --quiet 2> /dev/null")
+                        try bash("git -C '\(frameworkCheckoutPath)' clean -fdX --quiet 2> /dev/null")
+                    }
+                    catch {
+                        // Remove checkout if git reset fails for some reason
+                        // If the checkout is missing, SPM will automatically clone again in the next step
+                        FileManager.default.removeItem(atPath: frameworkCheckoutPath)
```
Comment (Jeehut) [inline Sources/AccioKit/Commands/Protocols/DependencyInstaller.swift]: Will this line do the same thing as `bash("rm -rf \(frameworkCheckoutPath)")`? And if so, what's the pro and cons of using `removeItem` instead of `rm -rf`? I'm guessing that if `removeItem` actually does the same thing, then it might be faster since it's not going the detour of bash and the `rm` command but directly does what's needed. In that case, we could replace all `rm -rf` calls with `removeItem`?

File: Sources/AccioKit/Commands/Protocols/DependencyInstaller.swift [hunk 2]
```diff
@@ -34,9 +34,16 @@ extension DependencyInstaller {
                 let frameworkCheckoutPath: String = checkoutsDirUrl.appendingPathComponent(fileName).path
 
                 if try FileManager.default.isDirectory(atPath: frameworkCheckoutPath) {
-                    try bash("git -C '\(frameworkCheckoutPath)' reset HEAD --hard --quiet 2> /dev/null")
-                    try bash("git -C '\(frameworkCheckoutPath)' clean -fd --quiet 2> /dev/null")
-                    try bash("git -C '\(frameworkCheckoutPath)' clean -fdX --quiet 2> /dev/null")
+                    do {
```
Comment (Jeehut) [inline Sources/AccioKit/Commands/Protocols/DependencyInstaller.swift:37]: Why do the `git` commands fail although I added `2> /dev/null`? Is it that only the standard output is redirected via `2>` but not the error output? If possible, I would prefer a fix of the `2>` rather than a try-catch.

**Review by Jeehut — COMMENTED** [review]
Thanks for this PR, basically I'm okay with merging it, but I'd get the two commented questions answered before doing so to keep consistency within the projects. For the same goal, I also have another question:

Given that we have `git -C` calls elsewhere too (and it's always the same three calls), shouln't we refactor this to a method and do the try-catch for all cases? The method might be throwing so we can handle the error case on the usage side.

File: Sources/AccioKit/Commands/Protocols/DependencyInstaller.swift (hunk 2 above)
Comment (fredpi) [reply Sources/AccioKit/Commands/Protocols/DependencyInstaller.swift:37]: I guess we could direct errors to `dev/null` by using `2>&1 /dev/null`.

However if an error occurs resetting, isn't it better to handle this by deleting the checkout so that Swift PM will redownload it? If we don't delete it and leave it as is, Swift PM will probably fail (wasn't this the reason the reset commands were implemented in the first place?).

File: Sources/AccioKit/Commands/Protocols/DependencyInstaller.swift (hunk 1 above)
Comment (fredpi) [reply Sources/AccioKit/Commands/Protocols/DependencyInstaller.swift]: Good idea to investigate this! Will look into it 👍

**Comment by fredpi** [comment]
> Given that we have `git -C` calls elsewhere too (and it's always the same three calls), shouln't we refactor this to a method and do the try-catch for all cases? The method might be throwing so we can handle the error case on the usage side.

If I looked it up properly, the other `git -C` calls happen after Swift PM resolves the dependencies. So if we delete the checked out repo, Swift PM won't come to the rescue and redownload it just afterwards. This is why I think, it's only suitable to apply this handling to the `git -C` commands run before `DependencyResolverService.shared.resolveDependencies()` is performed.

File: Sources/AccioKit/Commands/Protocols/DependencyInstaller.swift (hunk 2 above)
Comment (Jeehut) [reply Sources/AccioKit/Commands/Protocols/DependencyInstaller.swift:37]: Yes, handling the case and deleting the checkouts is probably the better approach. I was just suggesting the alternative to save time as it would also fix the issue. But feel free to continue with a more enhanced fix. 👍

**Comment by Jeehut** [comment]
@fredpi As I've already stated:

> The method might be throwing so we can handle the error case on the usage side.

What I mean there is that the refactored method should actually not include a `do-catch` but instead a `try` and be throwing. Then whenever we know what to do as an alternative when the reset fails, we could act accordingly (like deleting checkouts in the one case).

**Comment by fredpi** [comment]
@Dschee Sorry, I didn't read carefully -.-

**Comment by Jeehut** [comment]
No problem, I may have been ambiguous or at least not so clear. 😅

File: Sources/AccioKit/Commands/Protocols/DependencyInstaller.swift (hunk 1 above)
Comment (fredpi) [reply Sources/AccioKit/Commands/Protocols/DependencyInstaller.swift]: I opened up #41 to discuss this and will use the existing mechanism for this PR

**Comment by fredpi** [comment]
Should be good to merge now

File: Sources/AccioKit/Services/GitResetService.swift [hunk 3]
```diff
@@ -0,0 +1,12 @@
+import Foundation
+
+final class GitResetService {
+    static let shared = GitResetService()
+
+    private init() { }
+
+    func resetGit(atPath directory: String) throws {
+        try bash("git -C '\(directory)' reset HEAD --hard --quiet 2> /dev/null")
+        try bash("git -C '\(directory)' clean -fd --quiet 2> /dev/null")
```
Comment (Jeehut) [inline Sources/AccioKit/Services/GitResetService.swift:10]: Why is the `-fdX` variant missing here?

Comment (Jeehut) [reply Sources/AccioKit/Services/GitResetService.swift:10]: I think we should add a parameter to `resetGit` named something like `includeUntrackedFiles: Bool` and run the `-fdX` variant in that case, too.

**Review by Jeehut — CHANGES_REQUESTED** [review]
Nearly finished, but you missed the reset of untracked files (see [this commit](https://github.com/JamitLabs/Accio/commit/94323c14b16c4450990db2fcf495e8d31df37523)). See comments above.

**Comment by Jeehut** [comment]
Please also remove the [WIP] in the title when it's ready for merge. :)

File: Sources/AccioKit/Services/GitResetService.swift (hunk 3 above)
Comment (fredpi) [reply Sources/AccioKit/Services/GitResetService.swift:10]: For me the documentation I read sounded as calling the `-fdX` again after having called `-fd` was redundant, as `-fd` already did everything. Did I get that wrong?

Comment (Jeehut) [reply Sources/AccioKit/Services/GitResetService.swift:10]: Yes, you did get this wrong if I recall correctly. In my tests calling `-fd` wasn't enough to also reset files that were ignored by entries in the `.gitignore` file which could lead to problems with SwiftPM only projects. The `-rfX` call solved the issue via https://github.com/JamitLabs/Accio/commit/94323c14b16c4450990db2fcf495e8d31df37523. I don't think I made the commit "just in case", I'm pretty sure it solved a real problem.

Comment (fredpi) [reply Sources/AccioKit/Services/GitResetService.swift:10]: Okay, I'll adjust accordingly. Is there a special reason `-fdX` wasn't previously used everywhere? If not, we could just add it without making it configurable via a param.

Comment (Jeehut) [reply Sources/AccioKit/Services/GitResetService.swift:10]: I'm not sure, it might only be that I wanted to save time because it was not needed in some situations (and the reset could take some time). So I'd rather keep the parameter, but feel free to default it to `true`.

Comment (Jeehut) [reply Sources/AccioKit/Services/GitResetService.swift:10]: Please make sure to name the parameter with something better than `fdX`, for example `includeUntrackedFiles` as suggested above.

**Review by Jeehut — APPROVED** [review]

**Comment by Jeehut** [comment]
Looks good now, merging. Thanks for the PR! 🎉

**Comment by Jeehut** [comment]
Oh no, we forgot the Changelog entry. 😄
