### PR TITLE
Fix cache mixed up with different swift versions

### LINKED ISSUE #61: Cache mixes up different Swift versions
When caching frameworks, Accio differentiates between different Swift versions, so that a user having set `Xcode 10.2.1`  as their command line tools won't get cached frameworks originating from a user that has `Xcode 11` set as their command line tools. That's needed, as otherwise, Xcode would complain that the frameworks have been built with Swift 5.1, while the user is still running Xcode 10.2.1 with Swift 5.0.1.

So, it's perfectly valid to separate by Swift version. However, the implementation doesn't work properly, as the Swift version is retrieved on compile time of Accio:

```
static var swiftVersion: String {
    #if swift(>=6.0)
        return "Swift-6.0"
    #elseif swift(>=5.2)
        return "Swift-5.2"
    #elseif swift(>=5.1)
        return "Swift-5.1"
    #elseif swift(>=5.0)
        return "Swift-5.0"
    #else
        return "Swift-4.2"
    #endif
}
```

This works quite often, as the Accio-compile-time Swift version is likely to match the current Swift version, but in transition periods (like now, switching from `Swift 5.0` to `Swift 5.1`), this is a real issue: The folder that should store `Swift 5.0` builds may now also include `Swift 5.1` builds and the other way round.

To get things to work, the swift version should instead be retrieved via the `swift --version` command during runtime.

### PR DESCRIPTION
**Pull request by fredpi**
Fixes #61.

With this implementation, there is a differentiation between versions like "Swift 5.0" and "Swift 5.0.1". Previously, those have been treated equally. I'm indecisive how to handle this – what do you think?

Also, with module stability coming, we should allow a Swift 6.0 project to access cached Swift 5.1 builds, right?

### CODE REVIEW

**Comment by Jeehut** [comment]
Regarding the first point, I agree that differentiating Swift 5.0 from 5.0.1 is a good idea. Regarding backwards compatibility, see my comment in #64.

File: Sources/AccioKit/Services/CachedBuilderService.swift [hunk 1]
```diff
@@ -18,7 +24,12 @@ final class CachedBuilderService {
         }
 
         for framework in frameworksWithoutDuplicates {
-            if let cachedFrameworkProduct = try frameworkCachingService.cachedProduct(framework: framework, platform: platform) {
+            if
+                let cachedFrameworkProduct = try frameworkCachingService.cachedProduct(
+                framework: framework,
```
Comment (Jeehut) [inline Sources/AccioKit/Services/CachedBuilderService.swift]: Something is wrong with indentation here. I think what you meant was:

```swift
if 
    let cached = try frame.cached(
        framework: f,
        p: p,
    )
{
    framworkProducts
} else {
    ...
```

File: Sources/AccioKit/Services/SwiftVersionDetectorService.swift [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+
+enum SwiftVersionDetectorError: Error {
+    case unableToRunSwiftVersionCommand
+    case unableToParseSwiftVerisonCommand
+}
+
+class SwiftVersionDetectorService {
+    static let shared = SwiftVersionDetectorService()
+
+    func getCurrentSwiftVersion() throws -> String {
```
Comment (Jeehut) [inline Sources/AccioKit/Services/SwiftVersionDetectorService.swift:13]: I think we should cache this in a private property and use it if already detected once. That way we save us from multiple command line roundtrips.

**Review by Jeehut — COMMENTED** [review]
Thanks for this PR, looks good in the direction. But I'm not sure if we should inject the Swift version everywhere or simply use global state. While global state doesn't make sense in many cases, the Swift version is a good example for it IMO. The reason is that the Swift version really doesn't change during the entire process of running Accio commands, so injecting it everywhere is IMO more overhead and therefore less clean than global state. While some might disagree with me, I strongly believe that global state isn't _always_ bad. Alongside a cached property which holds the results of the first access, this should be a nicer API.

**Comment by fredpi** [comment]
Regarding global state of the Swift version:

> The reason is that the Swift version really doesn't change during the entire process of running Accio commands

While a change of the Swift version during runtime isn't that likely, it will have severe consequences if it happens. And scenarios, where it may happen, exist: e. g., when a new Xcode Beta release is published, the user, who set their command line tools to use this new version, may trigger `accio install`. Because the new Xcode release includes a new Swift version, many frameworks may not be in the cache already. So, the process takes a while, the user grabs a coffee, returns to their Mac and sets the command line tools to use the previous Xcode version again, while Accio is still running.

Now, when the Swift version has been cached, as you proposed, that's fine: Although the Swift version changed during the process of building, Accio will still store the build products in the proper place. We could therefore opt to do this caching. Still I think, it's semantically better to pass it around, as it may differ from build to build (which is currently not handled, but I suggest to do so, see next paragraph).

However, some frameworks might have been built with the Swift version that was set during the process, so not all frameworks belong to the same caching folder. In such a case, the Swift version should be determined right before each build and then stored in the build product model. We could opt for such a solution, but it would of course cause even more `swift --version` calls.

Given that having a framework built with Swift version `x` in the global cache for Swift Version `y`, where `x` != `y`, definitely has severe consequences for multiple users accessing this shared cache, and requires manual cleanup, I think we should be pretty precise about this. Maybe, one could infer the Swift Version from the `.framework` quite easily, so that a `swift --version` check isn't required each time?

Also, as the user himself will most likely not be able to use their frameworks built by Accio, when they changed the Swift version in the process of running Accio, we could also just stop Accio at all when a Swift version change is detected and drop a corresponding error message instead of performing the caching per Swift version.

**Comment by Jeehut** [comment]
IMHO the Swift version shouldn't change at all during the processing of one command. That would only cause confusion and make reproducing and fixing errors a nightmare. So, I'm definitely for returning with an error if the Swift version really ever changes during a command. I didn't think of that before, I was just referring to the thread of the command itself, not the commands we additionally run in console. But it's true that people might change Swift versions during a command.

**Comment by fredpi** [comment]
@Dschee Fine – I will...
- ... check how time-consuming it is to get the Swift version using `swift --version`
- ... check whether there are better options to retrieve it (e. g. via the built frameworks)
- ... implement monitoring of the Swift version, if suitable

**Comment by fredpi** [comment]
@Dschee  This is what I found out:

• Getting the Swift version via the `swift --version` command takes ~ 0.1 s for me
• It's possible to look for the Swift Header file (~`Headers/...-Swift.h`) in a framework and look up the Swift version there (it's included in a comment). This takes ~ 0.001 s on my machine, but doesn't work for some frameworks like `RxAtomic` where this file is missing for some reason...

Now, I implemented Swift version monitoring using the performant per-framework checking mechanism, having the `swift --version` command as a fallback. I'm wondering whether there is a better way to get the Swift version a framework was built with, also ensuring proper compatibility with frameworks like `RxAtomic`.

**Review by Jeehut — APPROVED** [review]
Looks good to me now. Merge at will.
